/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';

/**
 * 
 * @export
 * @interface ArticleCategoriesInnerProductImagesInner
 */
export interface ArticleCategoriesInnerProductImagesInner {
    /**
     * 
     * @type {number}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'alternativeText'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'caption'?: string;
    /**
     * 
     * @type {number}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'width'?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'height'?: number;
    /**
     * 
     * @type {any}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'formats'?: any;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'hash'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'ext'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'mime'?: string;
    /**
     * 
     * @type {number}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'previewUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'provider'?: string;
    /**
     * 
     * @type {any}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'provider_metadata'?: any;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'related'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'folder'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'folderPath'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof ArticleCategoriesInnerProductImagesInner
     */
    'localizations'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

