/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerArticlesInner } from './article-categories-inner-articles-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProduct } from './article-categories-inner-product';
// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';

/**
 * 
 * @export
 * @interface ArticleCategoriesInner
 */
export interface ArticleCategoriesInner {
    /**
     * 
     * @type {number}
     * @memberof ArticleCategoriesInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInner
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInner
     */
    'name'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProduct}
     * @memberof ArticleCategoriesInner
     */
    'product'?: ArticleCategoriesInnerProduct;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerArticlesInner>}
     * @memberof ArticleCategoriesInner
     */
    'articles'?: Array<ArticleCategoriesInnerArticlesInner>;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInner
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInner
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInner
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof ArticleCategoriesInner
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof ArticleCategoriesInner
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInner
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof ArticleCategoriesInner
     */
    'localizations'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

