/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { DynamicZoneCtaComponent } from './dynamic-zone-cta-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DynamicZoneRelatedProductsComponent } from './dynamic-zone-related-products-component';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedButtonComponent } from './shared-button-component';

/**
 * 
 * @export
 * @interface ArticleCategoriesInnerProductDynamicZoneInner
 */
export interface ArticleCategoriesInnerProductDynamicZoneInner {
    /**
     * 
     * @type {number}
     * @memberof ArticleCategoriesInnerProductDynamicZoneInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductDynamicZoneInner
     */
    '__component'?: ArticleCategoriesInnerProductDynamicZoneInnerComponentEnum;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductDynamicZoneInner
     */
    'heading'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategoriesInnerProductDynamicZoneInner
     */
    'sub_heading'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof ArticleCategoriesInnerProductDynamicZoneInner
     */
    'products'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {Array<SharedButtonComponent>}
     * @memberof ArticleCategoriesInnerProductDynamicZoneInner
     */
    'CTAs'?: Array<SharedButtonComponent>;
}

export const ArticleCategoriesInnerProductDynamicZoneInnerComponentEnum = {
    DynamicZoneCta: 'dynamic-zone.cta'
} as const;

export type ArticleCategoriesInnerProductDynamicZoneInnerComponentEnum = typeof ArticleCategoriesInnerProductDynamicZoneInnerComponentEnum[keyof typeof ArticleCategoriesInnerProductDynamicZoneInnerComponentEnum];


