/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { CardsGlobeCardComponent } from './cards-globe-card-component';
// May contain unused imports in some cases
// @ts-ignore
import type { CardsGraphCardComponent } from './cards-graph-card-component';
// May contain unused imports in some cases
// @ts-ignore
import type { CardsRayCardComponent } from './cards-ray-card-component';
// May contain unused imports in some cases
// @ts-ignore
import type { CardsSocialMediaCardComponent } from './cards-social-media-card-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DynamicZoneBrandsComponent } from './dynamic-zone-brands-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DynamicZoneCtaComponent } from './dynamic-zone-cta-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DynamicZoneFaqComponent } from './dynamic-zone-faq-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DynamicZoneFeaturesComponent } from './dynamic-zone-features-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DynamicZoneFormNextToSectionComponent } from './dynamic-zone-form-next-to-section-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DynamicZoneHeroComponent } from './dynamic-zone-hero-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DynamicZoneHowItWorksComponent } from './dynamic-zone-how-it-works-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DynamicZoneLaunchesComponent } from './dynamic-zone-launches-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DynamicZonePricingComponent } from './dynamic-zone-pricing-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DynamicZoneRelatedArticlesComponent } from './dynamic-zone-related-articles-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DynamicZoneRelatedProductsComponent } from './dynamic-zone-related-products-component';
// May contain unused imports in some cases
// @ts-ignore
import type { DynamicZoneTestimonialsComponent } from './dynamic-zone-testimonials-component';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedButtonComponent } from './shared-button-component';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedFormComponent } from './shared-form-component';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedLaunchesComponent } from './shared-launches-component';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedSectionComponent } from './shared-section-component';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedSocialMediaIconLinksComponent } from './shared-social-media-icon-links-component';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedStepsComponent } from './shared-steps-component';

/**
 * 
 * @export
 * @interface BlogPageRequestDataDynamicZoneInner
 */
export interface BlogPageRequestDataDynamicZoneInner {
    /**
     * 
     * @type {number}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    '__component'?: BlogPageRequestDataDynamicZoneInnerComponentEnum;
    /**
     * 
     * @type {string}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'heading'?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'sub_heading'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'testimonials'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'products'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'articles'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'plans'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {Array<SharedLaunchesComponent>}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'launches'?: Array<SharedLaunchesComponent>;
    /**
     * 
     * @type {Array<SharedStepsComponent>}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'steps'?: Array<SharedStepsComponent>;
    /**
     * 
     * @type {Array<SharedButtonComponent>}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'CTAs'?: Array<SharedButtonComponent>;
    /**
     * 
     * @type {SharedFormComponent}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'form'?: SharedFormComponent;
    /**
     * 
     * @type {SharedSectionComponent}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'section'?: SharedSectionComponent;
    /**
     * 
     * @type {Array<SharedSocialMediaIconLinksComponent>}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'social_media_icon_links'?: Array<SharedSocialMediaIconLinksComponent>;
    /**
     * 
     * @type {CardsGlobeCardComponent}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'globe_card'?: CardsGlobeCardComponent;
    /**
     * 
     * @type {CardsRayCardComponent}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'ray_card'?: CardsRayCardComponent;
    /**
     * 
     * @type {CardsGraphCardComponent}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'graph_card'?: CardsGraphCardComponent;
    /**
     * 
     * @type {CardsSocialMediaCardComponent}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'social_media_card'?: CardsSocialMediaCardComponent;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'faqs'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof BlogPageRequestDataDynamicZoneInner
     */
    'logos'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

export const BlogPageRequestDataDynamicZoneInnerComponentEnum = {
    DynamicZoneBrands: 'dynamic-zone.brands'
} as const;

export type BlogPageRequestDataDynamicZoneInnerComponentEnum = typeof BlogPageRequestDataDynamicZoneInnerComponentEnum[keyof typeof BlogPageRequestDataDynamicZoneInnerComponentEnum];


