/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleRequestDataCategoriesInner } from './article-request-data-categories-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { BlogPageRequestDataDynamicZoneInner } from './blog-page-request-data-dynamic-zone-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedSeoComponent } from './shared-seo-component';

/**
 * 
 * @export
 * @interface BlogPageRequestData
 */
export interface BlogPageRequestData {
    /**
     * 
     * @type {SharedSeoComponent}
     * @memberof BlogPageRequestData
     */
    'seo'?: SharedSeoComponent;
    /**
     * 
     * @type {string}
     * @memberof BlogPageRequestData
     */
    'heading'?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogPageRequestData
     */
    'sub_heading'?: string;
    /**
     * 
     * @type {Array<BlogPageRequestDataDynamicZoneInner>}
     * @memberof BlogPageRequestData
     */
    'dynamic_zone'?: Array<BlogPageRequestDataDynamicZoneInner>;
    /**
     * 
     * @type {string}
     * @memberof BlogPageRequestData
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof BlogPageRequestData
     */
    'localizations'?: Array<ArticleRequestDataCategoriesInner>;
}

