/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';

/**
 * 
 * @export
 * @interface CardsSocialMediaCardComponent
 */
export interface CardsSocialMediaCardComponent {
    /**
     * 
     * @type {number}
     * @memberof CardsSocialMediaCardComponent
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CardsSocialMediaCardComponent
     */
    'Title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardsSocialMediaCardComponent
     */
    'Description'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof CardsSocialMediaCardComponent
     */
    'logos'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {string}
     * @memberof CardsSocialMediaCardComponent
     */
    'span'?: CardsSocialMediaCardComponentSpanEnum;
}

export const CardsSocialMediaCardComponentSpanEnum = {
    One: 'one',
    Two: 'two',
    Three: 'three'
} as const;

export type CardsSocialMediaCardComponentSpanEnum = typeof CardsSocialMediaCardComponentSpanEnum[keyof typeof CardsSocialMediaCardComponentSpanEnum];


