/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleRequestDataCategoriesInner } from './article-request-data-categories-inner';

/**
 * 
 * @export
 * @interface CategoryRequestData
 */
export interface CategoryRequestData {
    /**
     * 
     * @type {string}
     * @memberof CategoryRequestData
     */
    'name'?: string;
    /**
     * 
     * @type {ArticleRequestDataCategoriesInner}
     * @memberof CategoryRequestData
     */
    'product'?: ArticleRequestDataCategoriesInner;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof CategoryRequestData
     */
    'articles'?: Array<ArticleRequestDataCategoriesInner>;
    /**
     * 
     * @type {string}
     * @memberof CategoryRequestData
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof CategoryRequestData
     */
    'localizations'?: Array<ArticleRequestDataCategoriesInner>;
}

