/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';

/**
 * 
 * @export
 * @interface CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
 */
export interface CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner {
    /**
     * 
     * @type {number}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'action'?: string;
    /**
     * 
     * @type {any}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'actionParameters'?: any;
    /**
     * 
     * @type {string}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'subject'?: string;
    /**
     * 
     * @type {any}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'properties'?: any;
    /**
     * 
     * @type {any}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'conditions'?: any;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'role'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof CategoryProductImagesInnerFolderFilesInnerCreatedByRolesInnerPermissionsInner
     */
    'localizations'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

