/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductDynamicZoneInner } from './article-categories-inner-product-dynamic-zone-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductPlansInner } from './article-categories-inner-product-plans-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { CategoryProductCategoriesInner } from './category-product-categories-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { CategoryProductImagesInner } from './category-product-images-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedPerksComponent } from './shared-perks-component';

/**
 * 
 * @export
 * @interface CategoryProduct
 */
export interface CategoryProduct {
    /**
     * 
     * @type {number}
     * @memberof CategoryProduct
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryProduct
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryProduct
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof CategoryProduct
     */
    'price'?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryProduct
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryProduct
     */
    'slug'?: string;
    /**
     * 
     * @type {Array<CategoryProductImagesInner>}
     * @memberof CategoryProduct
     */
    'images'?: Array<CategoryProductImagesInner>;
    /**
     * 
     * @type {Array<SharedPerksComponent>}
     * @memberof CategoryProduct
     */
    'perks'?: Array<SharedPerksComponent>;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductPlansInner>}
     * @memberof CategoryProduct
     */
    'plans'?: Array<ArticleCategoriesInnerProductPlansInner>;
    /**
     * 
     * @type {Array<CategoryProductCategoriesInner>}
     * @memberof CategoryProduct
     */
    'categories'?: Array<CategoryProductCategoriesInner>;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductDynamicZoneInner>}
     * @memberof CategoryProduct
     */
    'dynamic_zone'?: Array<ArticleCategoriesInnerProductDynamicZoneInner>;
    /**
     * 
     * @type {boolean}
     * @memberof CategoryProduct
     */
    'featured'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CategoryProduct
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryProduct
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryProduct
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof CategoryProduct
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof CategoryProduct
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof CategoryProduct
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof CategoryProduct
     */
    'localizations'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

