/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';

/**
 * 
 * @export
 * @interface ClientStageCustomersInnerStage
 */
export interface ClientStageCustomersInnerStage {
    /**
     * 
     * @type {number}
     * @memberof ClientStageCustomersInnerStage
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientStageCustomersInnerStage
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientStageCustomersInnerStage
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientStageCustomersInnerStage
     */
    'purpose'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientStageCustomersInnerStage
     */
    'focus_on'?: string;
    /**
     * 
     * @type {number}
     * @memberof ClientStageCustomersInnerStage
     */
    'follow_up_automation_days'?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientStageCustomersInnerStage
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ClientStageCustomersInnerStage
     */
    'isActiveStage'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientStageCustomersInnerStage
     */
    'isSOIStage'?: boolean;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof ClientStageCustomersInnerStage
     */
    'customers'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {string}
     * @memberof ClientStageCustomersInnerStage
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientStageCustomersInnerStage
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientStageCustomersInnerStage
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof ClientStageCustomersInnerStage
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof ClientStageCustomersInnerStage
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof ClientStageCustomersInnerStage
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof ClientStageCustomersInnerStage
     */
    'localizations'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

