/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleRequestDataCategoriesInner } from './article-request-data-categories-inner';

/**
 * 
 * @export
 * @interface DealRequestData
 */
export interface DealRequestData {
    /**
     * 
     * @type {string}
     * @memberof DealRequestData
     */
    'title': string;
    /**
     * 
     * @type {ArticleRequestDataCategoriesInner}
     * @memberof DealRequestData
     */
    'status'?: ArticleRequestDataCategoriesInner;
    /**
     * 
     * @type {number}
     * @memberof DealRequestData
     */
    'dealValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof DealRequestData
     */
    'dealDate'?: string;
    /**
     * 
     * @type {ArticleRequestDataCategoriesInner}
     * @memberof DealRequestData
     */
    'customer'?: ArticleRequestDataCategoriesInner;
    /**
     * 
     * @type {ArticleRequestDataCategoriesInner}
     * @memberof DealRequestData
     */
    'property'?: ArticleRequestDataCategoriesInner;
    /**
     * 
     * @type {ArticleRequestDataCategoriesInner}
     * @memberof DealRequestData
     */
    'agent'?: ArticleRequestDataCategoriesInner;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof DealRequestData
     */
    'notes'?: Array<ArticleRequestDataCategoriesInner>;
    /**
     * 
     * @type {string}
     * @memberof DealRequestData
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof DealRequestData
     */
    'localizations'?: Array<ArticleRequestDataCategoriesInner>;
}

