/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ClientStageCustomersInnerAgent } from './client-stage-customers-inner-agent';
// May contain unused imports in some cases
// @ts-ignore
import type { ClientStageCustomersInnerDealsInner } from './client-stage-customers-inner-deals-inner';

/**
 * 
 * @export
 * @interface DealStatusCustomersInner
 */
export interface DealStatusCustomersInner {
    /**
     * 
     * @type {number}
     * @memberof DealStatusCustomersInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof DealStatusCustomersInner
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DealStatusCustomersInner
     */
    'fullName'?: string;
    /**
     * 
     * @type {string}
     * @memberof DealStatusCustomersInner
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof DealStatusCustomersInner
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof DealStatusCustomersInner
     */
    'source'?: DealStatusCustomersInnerSourceEnum;
    /**
     * 
     * @type {ClientStageCustomersInnerAgent}
     * @memberof DealStatusCustomersInner
     */
    'agent'?: ClientStageCustomersInnerAgent;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof DealStatusCustomersInner
     */
    'stage'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {Array<ClientStageCustomersInnerDealsInner>}
     * @memberof DealStatusCustomersInner
     */
    'deals'?: Array<ClientStageCustomersInnerDealsInner>;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof DealStatusCustomersInner
     */
    'notes'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {string}
     * @memberof DealStatusCustomersInner
     */
    'lastContacted'?: string;
    /**
     * 
     * @type {string}
     * @memberof DealStatusCustomersInner
     */
    'nextFollowUp'?: string;
    /**
     * 
     * @type {string}
     * @memberof DealStatusCustomersInner
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof DealStatusCustomersInner
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof DealStatusCustomersInner
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof DealStatusCustomersInner
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof DealStatusCustomersInner
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof DealStatusCustomersInner
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof DealStatusCustomersInner
     */
    'localizations'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

export const DealStatusCustomersInnerSourceEnum = {
    Website: 'website',
    Facebook: 'facebook',
    Zalo: 'zalo',
    Referral: 'referral',
    Event: 'event',
    Other: 'other'
} as const;

export type DealStatusCustomersInnerSourceEnum = typeof DealStatusCustomersInnerSourceEnum[keyof typeof DealStatusCustomersInnerSourceEnum];


