/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';

/**
 * 
 * @export
 * @interface DynamicZoneRelatedArticlesComponent
 */
export interface DynamicZoneRelatedArticlesComponent {
    /**
     * 
     * @type {number}
     * @memberof DynamicZoneRelatedArticlesComponent
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof DynamicZoneRelatedArticlesComponent
     */
    '__component'?: DynamicZoneRelatedArticlesComponentComponentEnum;
    /**
     * 
     * @type {string}
     * @memberof DynamicZoneRelatedArticlesComponent
     */
    'heading'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicZoneRelatedArticlesComponent
     */
    'sub_heading'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof DynamicZoneRelatedArticlesComponent
     */
    'articles'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

export const DynamicZoneRelatedArticlesComponentComponentEnum = {
    DynamicZoneRelatedArticles: 'dynamic-zone.related-articles'
} as const;

export type DynamicZoneRelatedArticlesComponentComponentEnum = typeof DynamicZoneRelatedArticlesComponentComponentEnum[keyof typeof DynamicZoneRelatedArticlesComponentComponentEnum];


