/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SharedButtonComponent } from './shared-button-component';

/**
 * 
 * @export
 * @interface DynamicZoneCtaComponent
 */
export interface DynamicZoneCtaComponent {
    /**
     * 
     * @type {number}
     * @memberof DynamicZoneCtaComponent
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof DynamicZoneCtaComponent
     */
    '__component'?: DynamicZoneCtaComponentComponentEnum;
    /**
     * 
     * @type {string}
     * @memberof DynamicZoneCtaComponent
     */
    'heading'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicZoneCtaComponent
     */
    'sub_heading'?: string;
    /**
     * 
     * @type {Array<SharedButtonComponent>}
     * @memberof DynamicZoneCtaComponent
     */
    'CTAs'?: Array<SharedButtonComponent>;
}

export const DynamicZoneCtaComponentComponentEnum = {
    DynamicZoneCta: 'dynamic-zone.cta'
} as const;

export type DynamicZoneCtaComponentComponentEnum = typeof DynamicZoneCtaComponentComponentEnum[keyof typeof DynamicZoneCtaComponentComponentEnum];


