/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';

/**
 * 
 * @export
 * @interface DynamicZoneBrandsComponent
 */
export interface DynamicZoneBrandsComponent {
    /**
     * 
     * @type {number}
     * @memberof DynamicZoneBrandsComponent
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof DynamicZoneBrandsComponent
     */
    '__component'?: DynamicZoneBrandsComponentComponentEnum;
    /**
     * 
     * @type {string}
     * @memberof DynamicZoneBrandsComponent
     */
    'heading'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicZoneBrandsComponent
     */
    'sub_heading'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof DynamicZoneBrandsComponent
     */
    'logos'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

export const DynamicZoneBrandsComponentComponentEnum = {
    DynamicZoneBrands: 'dynamic-zone.brands'
} as const;

export type DynamicZoneBrandsComponentComponentEnum = typeof DynamicZoneBrandsComponentComponentEnum[keyof typeof DynamicZoneBrandsComponentComponentEnum];


