/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { CategoryProductImagesInnerFolderFilesInnerCreatedBy } from './category-product-images-inner-folder-files-inner-created-by';
// May contain unused imports in some cases
// @ts-ignore
import type { FaqLocalizationsInner } from './faq-localizations-inner';

/**
 * 
 * @export
 * @interface Faq
 */
export interface Faq {
    /**
     * 
     * @type {number}
     * @memberof Faq
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Faq
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Faq
     */
    'question'?: string;
    /**
     * 
     * @type {string}
     * @memberof Faq
     */
    'answer'?: string;
    /**
     * 
     * @type {string}
     * @memberof Faq
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Faq
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Faq
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {CategoryProductImagesInnerFolderFilesInnerCreatedBy}
     * @memberof Faq
     */
    'createdBy'?: CategoryProductImagesInnerFolderFilesInnerCreatedBy;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Faq
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof Faq
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<FaqLocalizationsInner>}
     * @memberof Faq
     */
    'localizations'?: Array<FaqLocalizationsInner>;
}

