/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GlobalFooterComponent } from './global-footer-component';
// May contain unused imports in some cases
// @ts-ignore
import type { GlobalNavbarComponent } from './global-navbar-component';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedSeoComponent } from './shared-seo-component';

/**
 * 
 * @export
 * @interface GlobalLocalizationsInner
 */
export interface GlobalLocalizationsInner {
    /**
     * 
     * @type {number}
     * @memberof GlobalLocalizationsInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof GlobalLocalizationsInner
     */
    'documentId'?: string;
    /**
     * 
     * @type {SharedSeoComponent}
     * @memberof GlobalLocalizationsInner
     */
    'seo'?: SharedSeoComponent;
    /**
     * 
     * @type {GlobalNavbarComponent}
     * @memberof GlobalLocalizationsInner
     */
    'navbar'?: GlobalNavbarComponent;
    /**
     * 
     * @type {GlobalFooterComponent}
     * @memberof GlobalLocalizationsInner
     */
    'footer'?: GlobalFooterComponent;
    /**
     * 
     * @type {string}
     * @memberof GlobalLocalizationsInner
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalLocalizationsInner
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalLocalizationsInner
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof GlobalLocalizationsInner
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof GlobalLocalizationsInner
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof GlobalLocalizationsInner
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof GlobalLocalizationsInner
     */
    'localizations'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

