/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedLinkComponent } from './shared-link-component';

/**
 * 
 * @export
 * @interface GlobalNavbarComponent
 */
export interface GlobalNavbarComponent {
    /**
     * 
     * @type {number}
     * @memberof GlobalNavbarComponent
     */
    'id'?: number;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof GlobalNavbarComponent
     */
    'logo'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {Array<SharedLinkComponent>}
     * @memberof GlobalNavbarComponent
     */
    'left_navbar_items'?: Array<SharedLinkComponent>;
    /**
     * 
     * @type {Array<SharedLinkComponent>}
     * @memberof GlobalNavbarComponent
     */
    'right_navbar_items'?: Array<SharedLinkComponent>;
}

