/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleRequestDataCategoriesInner } from './article-request-data-categories-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GlobalFooterComponent } from './global-footer-component';
// May contain unused imports in some cases
// @ts-ignore
import type { GlobalNavbarComponent } from './global-navbar-component';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedSeoComponent } from './shared-seo-component';

/**
 * 
 * @export
 * @interface GlobalRequestData
 */
export interface GlobalRequestData {
    /**
     * 
     * @type {SharedSeoComponent}
     * @memberof GlobalRequestData
     */
    'seo'?: SharedSeoComponent;
    /**
     * 
     * @type {GlobalNavbarComponent}
     * @memberof GlobalRequestData
     */
    'navbar'?: GlobalNavbarComponent;
    /**
     * 
     * @type {GlobalFooterComponent}
     * @memberof GlobalRequestData
     */
    'footer'?: GlobalFooterComponent;
    /**
     * 
     * @type {string}
     * @memberof GlobalRequestData
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof GlobalRequestData
     */
    'localizations'?: Array<ArticleRequestDataCategoriesInner>;
}

