/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { CategoryProductImagesInner } from './category-product-images-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { LogoLocalizationsInner } from './logo-localizations-inner';

/**
 * 
 * @export
 * @interface Logo
 */
export interface Logo {
    /**
     * 
     * @type {number}
     * @memberof Logo
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Logo
     */
    'documentId'?: string;
    /**
     * 
     * @type {CategoryProductImagesInner}
     * @memberof Logo
     */
    'image': CategoryProductImagesInner;
    /**
     * 
     * @type {string}
     * @memberof Logo
     */
    'company'?: string;
    /**
     * 
     * @type {string}
     * @memberof Logo
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Logo
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Logo
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Logo
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Logo
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof Logo
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<LogoLocalizationsInner>}
     * @memberof Logo
     */
    'localizations'?: Array<LogoLocalizationsInner>;
}

