/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ClientStageCustomersInnerAgent } from './client-stage-customers-inner-agent';
// May contain unused imports in some cases
// @ts-ignore
import type { NoteCustomer } from './note-customer';

/**
 * 
 * @export
 * @interface Note
 */
export interface Note {
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    'content': string;
    /**
     * 
     * @type {ClientStageCustomersInnerAgent}
     * @memberof Note
     */
    'createdByUser'?: ClientStageCustomersInnerAgent;
    /**
     * 
     * @type {NoteCustomer}
     * @memberof Note
     */
    'customer'?: NoteCustomer;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Note
     */
    'deal'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Note
     */
    'property'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Note
     */
    'task'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Note
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Note
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof Note
     */
    'localizations'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

