/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { PageLocalizationsInner } from './page-localizations-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { PageRequestDataDynamicZoneInner } from './page-request-data-dynamic-zone-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedSeoComponent } from './shared-seo-component';

/**
 * 
 * @export
 * @interface Page
 */
export interface Page {
    /**
     * 
     * @type {number}
     * @memberof Page
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Page
     */
    'documentId'?: string;
    /**
     * 
     * @type {SharedSeoComponent}
     * @memberof Page
     */
    'seo'?: SharedSeoComponent;
    /**
     * 
     * @type {string}
     * @memberof Page
     */
    'slug': string;
    /**
     * 
     * @type {Array<PageRequestDataDynamicZoneInner>}
     * @memberof Page
     */
    'dynamic_zone'?: Array<PageRequestDataDynamicZoneInner>;
    /**
     * 
     * @type {string}
     * @memberof Page
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Page
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Page
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Page
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Page
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof Page
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<PageLocalizationsInner>}
     * @memberof Page
     */
    'localizations'?: Array<PageLocalizationsInner>;
}

