/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleRequestDataCategoriesInner } from './article-request-data-categories-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedButtonComponent } from './shared-button-component';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedPerksComponent } from './shared-perks-component';

/**
 * 
 * @export
 * @interface PlanRequestData
 */
export interface PlanRequestData {
    /**
     * 
     * @type {string}
     * @memberof PlanRequestData
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof PlanRequestData
     */
    'price'?: number;
    /**
     * 
     * @type {string}
     * @memberof PlanRequestData
     */
    'sub_text'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PlanRequestData
     */
    'featured'?: boolean;
    /**
     * 
     * @type {SharedButtonComponent}
     * @memberof PlanRequestData
     */
    'CTA'?: SharedButtonComponent;
    /**
     * 
     * @type {Array<SharedPerksComponent>}
     * @memberof PlanRequestData
     */
    'perks'?: Array<SharedPerksComponent>;
    /**
     * 
     * @type {Array<SharedPerksComponent>}
     * @memberof PlanRequestData
     */
    'additional_perks'?: Array<SharedPerksComponent>;
    /**
     * 
     * @type {ArticleRequestDataCategoriesInner}
     * @memberof PlanRequestData
     */
    'product'?: ArticleRequestDataCategoriesInner;
    /**
     * 
     * @type {string}
     * @memberof PlanRequestData
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof PlanRequestData
     */
    'localizations'?: Array<ArticleRequestDataCategoriesInner>;
}

