/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PlanRequestData } from './plan-request-data';

/**
 * 
 * @export
 * @interface PlanRequest
 */
export interface PlanRequest {
    /**
     * 
     * @type {PlanRequestData}
     * @memberof PlanRequest
     */
    'data': PlanRequestData;
}

