/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { CategoryProduct } from './category-product';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedButtonComponent } from './shared-button-component';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedPerksComponent } from './shared-perks-component';

/**
 * 
 * @export
 * @interface Plan
 */
export interface Plan {
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    'price'?: number;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    'sub_text'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Plan
     */
    'featured'?: boolean;
    /**
     * 
     * @type {SharedButtonComponent}
     * @memberof Plan
     */
    'CTA'?: SharedButtonComponent;
    /**
     * 
     * @type {Array<SharedPerksComponent>}
     * @memberof Plan
     */
    'perks'?: Array<SharedPerksComponent>;
    /**
     * 
     * @type {Array<SharedPerksComponent>}
     * @memberof Plan
     */
    'additional_perks'?: Array<SharedPerksComponent>;
    /**
     * 
     * @type {CategoryProduct}
     * @memberof Plan
     */
    'product'?: CategoryProduct;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Plan
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Plan
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof Plan
     */
    'localizations'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

