/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductDynamicZoneInner } from './article-categories-inner-product-dynamic-zone-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ArticleRequestDataCategoriesInner } from './article-request-data-categories-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedPerksComponent } from './shared-perks-component';

/**
 * 
 * @export
 * @interface ProductRequestData
 */
export interface ProductRequestData {
    /**
     * 
     * @type {string}
     * @memberof ProductRequestData
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductRequestData
     */
    'price'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductRequestData
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductRequestData
     */
    'slug'?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof ProductRequestData
     */
    'images'?: Array<ArticleRequestDataCategoriesInner>;
    /**
     * 
     * @type {Array<SharedPerksComponent>}
     * @memberof ProductRequestData
     */
    'perks'?: Array<SharedPerksComponent>;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof ProductRequestData
     */
    'plans'?: Array<ArticleRequestDataCategoriesInner>;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof ProductRequestData
     */
    'categories'?: Array<ArticleRequestDataCategoriesInner>;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductDynamicZoneInner>}
     * @memberof ProductRequestData
     */
    'dynamic_zone'?: Array<ArticleCategoriesInnerProductDynamicZoneInner>;
    /**
     * 
     * @type {boolean}
     * @memberof ProductRequestData
     */
    'featured'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductRequestData
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof ProductRequestData
     */
    'localizations'?: Array<ArticleRequestDataCategoriesInner>;
}

