/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { PropertyListedByRole } from './property-listed-by-role';

/**
 * 
 * @export
 * @interface PropertyListedBy
 */
export interface PropertyListedBy {
    /**
     * 
     * @type {number}
     * @memberof PropertyListedBy
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedBy
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedBy
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedBy
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedBy
     */
    'provider'?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedBy
     */
    'resetPasswordToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedBy
     */
    'confirmationToken'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PropertyListedBy
     */
    'confirmed'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PropertyListedBy
     */
    'blocked'?: boolean;
    /**
     * 
     * @type {PropertyListedByRole}
     * @memberof PropertyListedBy
     */
    'role'?: PropertyListedByRole;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedBy
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedBy
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedBy
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof PropertyListedBy
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof PropertyListedBy
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedBy
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof PropertyListedBy
     */
    'localizations'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

