/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { PropertyListedByRolePermissionsInner } from './property-listed-by-role-permissions-inner';

/**
 * 
 * @export
 * @interface PropertyListedByRole
 */
export interface PropertyListedByRole {
    /**
     * 
     * @type {number}
     * @memberof PropertyListedByRole
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedByRole
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedByRole
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedByRole
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedByRole
     */
    'type'?: string;
    /**
     * 
     * @type {Array<PropertyListedByRolePermissionsInner>}
     * @memberof PropertyListedByRole
     */
    'permissions'?: Array<PropertyListedByRolePermissionsInner>;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof PropertyListedByRole
     */
    'users'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedByRole
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedByRole
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedByRole
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof PropertyListedByRole
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof PropertyListedByRole
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof PropertyListedByRole
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof PropertyListedByRole
     */
    'localizations'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

