/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { CategoryProductImagesInner } from './category-product-images-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { PropertyDealsInner } from './property-deals-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { PropertyListedBy } from './property-listed-by';

/**
 * 
 * @export
 * @interface Property
 */
export interface Property {
    /**
     * 
     * @type {number}
     * @memberof Property
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Property
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Property
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof Property
     */
    'propertyType'?: PropertyPropertyTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Property
     */
    'location'?: string;
    /**
     * 
     * @type {number}
     * @memberof Property
     */
    'price'?: number;
    /**
     * 
     * @type {number}
     * @memberof Property
     */
    'area'?: number;
    /**
     * 
     * @type {number}
     * @memberof Property
     */
    'bedrooms'?: number;
    /**
     * 
     * @type {number}
     * @memberof Property
     */
    'bathrooms'?: number;
    /**
     * 
     * @type {string}
     * @memberof Property
     */
    'status'?: PropertyStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Property
     */
    'description'?: string;
    /**
     * 
     * @type {Array<CategoryProductImagesInner>}
     * @memberof Property
     */
    'images'?: Array<CategoryProductImagesInner>;
    /**
     * 
     * @type {PropertyListedBy}
     * @memberof Property
     */
    'listedBy'?: PropertyListedBy;
    /**
     * 
     * @type {Array<PropertyDealsInner>}
     * @memberof Property
     */
    'deals'?: Array<PropertyDealsInner>;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof Property
     */
    'notes'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {string}
     * @memberof Property
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Property
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Property
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Property
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Property
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof Property
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof Property
     */
    'localizations'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

export const PropertyPropertyTypeEnum = {
    Apartment: 'apartment',
    House: 'house',
    Land: 'land',
    Villa: 'villa',
    Commercial: 'commercial',
    Other: 'other'
} as const;

export type PropertyPropertyTypeEnum = typeof PropertyPropertyTypeEnum[keyof typeof PropertyPropertyTypeEnum];
export const PropertyStatusEnum = {
    Available: 'available',
    Sold: 'sold',
    Pending: 'pending',
    OffMarket: 'off-market'
} as const;

export type PropertyStatusEnum = typeof PropertyStatusEnum[keyof typeof PropertyStatusEnum];


