/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleRequestDataCategoriesInner } from './article-request-data-categories-inner';

/**
 * 
 * @export
 * @interface PropertyRequestData
 */
export interface PropertyRequestData {
    /**
     * 
     * @type {string}
     * @memberof PropertyRequestData
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof PropertyRequestData
     */
    'propertyType'?: PropertyRequestDataPropertyTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PropertyRequestData
     */
    'location'?: string;
    /**
     * 
     * @type {number}
     * @memberof PropertyRequestData
     */
    'price'?: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyRequestData
     */
    'area'?: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyRequestData
     */
    'bedrooms'?: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyRequestData
     */
    'bathrooms'?: number;
    /**
     * 
     * @type {string}
     * @memberof PropertyRequestData
     */
    'status'?: PropertyRequestDataStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PropertyRequestData
     */
    'description'?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof PropertyRequestData
     */
    'images'?: Array<ArticleRequestDataCategoriesInner>;
    /**
     * 
     * @type {ArticleRequestDataCategoriesInner}
     * @memberof PropertyRequestData
     */
    'listedBy'?: ArticleRequestDataCategoriesInner;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof PropertyRequestData
     */
    'deals'?: Array<ArticleRequestDataCategoriesInner>;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof PropertyRequestData
     */
    'notes'?: Array<ArticleRequestDataCategoriesInner>;
    /**
     * 
     * @type {string}
     * @memberof PropertyRequestData
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof PropertyRequestData
     */
    'localizations'?: Array<ArticleRequestDataCategoriesInner>;
}

export const PropertyRequestDataPropertyTypeEnum = {
    Apartment: 'apartment',
    House: 'house',
    Land: 'land',
    Villa: 'villa',
    Commercial: 'commercial',
    Other: 'other'
} as const;

export type PropertyRequestDataPropertyTypeEnum = typeof PropertyRequestDataPropertyTypeEnum[keyof typeof PropertyRequestDataPropertyTypeEnum];
export const PropertyRequestDataStatusEnum = {
    Available: 'available',
    Sold: 'sold',
    Pending: 'pending',
    OffMarket: 'off-market'
} as const;

export type PropertyRequestDataStatusEnum = typeof PropertyRequestDataStatusEnum[keyof typeof PropertyRequestDataStatusEnum];


