/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SharedButtonComponent
 */
export interface SharedButtonComponent {
    /**
     * 
     * @type {number}
     * @memberof SharedButtonComponent
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SharedButtonComponent
     */
    'text'?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedButtonComponent
     */
    'URL'?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedButtonComponent
     */
    'target'?: SharedButtonComponentTargetEnum;
    /**
     * 
     * @type {string}
     * @memberof SharedButtonComponent
     */
    'variant'?: SharedButtonComponentVariantEnum;
}

export const SharedButtonComponentTargetEnum = {
    Blank: '_blank',
    Self: '_self',
    Parent: '_parent',
    Top: '_top'
} as const;

export type SharedButtonComponentTargetEnum = typeof SharedButtonComponentTargetEnum[keyof typeof SharedButtonComponentTargetEnum];
export const SharedButtonComponentVariantEnum = {
    Simple: 'simple',
    Outline: 'outline',
    Primary: 'primary',
    Muted: 'muted'
} as const;

export type SharedButtonComponentVariantEnum = typeof SharedButtonComponentVariantEnum[keyof typeof SharedButtonComponentVariantEnum];


