/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInner } from './article-categories-inner-product-images-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedLinkComponent } from './shared-link-component';

/**
 * 
 * @export
 * @interface SharedSocialMediaIconLinksComponent
 */
export interface SharedSocialMediaIconLinksComponent {
    /**
     * 
     * @type {number}
     * @memberof SharedSocialMediaIconLinksComponent
     */
    'id'?: number;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInner}
     * @memberof SharedSocialMediaIconLinksComponent
     */
    'image'?: ArticleCategoriesInnerProductImagesInner;
    /**
     * 
     * @type {Array<SharedLinkComponent>}
     * @memberof SharedSocialMediaIconLinksComponent
     */
    'link'?: Array<SharedLinkComponent>;
}

