/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SharedLinkComponent
 */
export interface SharedLinkComponent {
    /**
     * 
     * @type {number}
     * @memberof SharedLinkComponent
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SharedLinkComponent
     */
    'text'?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedLinkComponent
     */
    'URL'?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedLinkComponent
     */
    'target'?: SharedLinkComponentTargetEnum;
}

export const SharedLinkComponentTargetEnum = {
    Blank: '_blank',
    Self: '_self',
    Parent: '_parent',
    Top: '_top'
} as const;

export type SharedLinkComponentTargetEnum = typeof SharedLinkComponentTargetEnum[keyof typeof SharedLinkComponentTargetEnum];


