/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleRequestDataCategoriesInner } from './article-request-data-categories-inner';

/**
 * 
 * @export
 * @interface TaskRequestData
 */
export interface TaskRequestData {
    /**
     * 
     * @type {string}
     * @memberof TaskRequestData
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof TaskRequestData
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRequestData
     */
    'dueDate'?: string;
    /**
     * 
     * @type {ArticleRequestDataCategoriesInner}
     * @memberof TaskRequestData
     */
    'assignedTo'?: ArticleRequestDataCategoriesInner;
    /**
     * 
     * @type {string}
     * @memberof TaskRequestData
     */
    'status'?: TaskRequestDataStatusEnum;
    /**
     * 
     * @type {ArticleRequestDataCategoriesInner}
     * @memberof TaskRequestData
     */
    'relatedDeal'?: ArticleRequestDataCategoriesInner;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof TaskRequestData
     */
    'notes'?: Array<ArticleRequestDataCategoriesInner>;
    /**
     * 
     * @type {string}
     * @memberof TaskRequestData
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleRequestDataCategoriesInner>}
     * @memberof TaskRequestData
     */
    'localizations'?: Array<ArticleRequestDataCategoriesInner>;
}

export const TaskRequestDataStatusEnum = {
    Pending: 'pending',
    InProgress: 'in_progress',
    Completed: 'completed'
} as const;

export type TaskRequestDataStatusEnum = typeof TaskRequestDataStatusEnum[keyof typeof TaskRequestDataStatusEnum];


