/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { TaskRelatedDealStatus } from './task-related-deal-status';

/**
 * 
 * @export
 * @interface TaskRelatedDeal
 */
export interface TaskRelatedDeal {
    /**
     * 
     * @type {number}
     * @memberof TaskRelatedDeal
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDeal
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDeal
     */
    'title'?: string;
    /**
     * 
     * @type {TaskRelatedDealStatus}
     * @memberof TaskRelatedDeal
     */
    'status'?: TaskRelatedDealStatus;
    /**
     * 
     * @type {number}
     * @memberof TaskRelatedDeal
     */
    'dealValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDeal
     */
    'dealDate'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof TaskRelatedDeal
     */
    'customer'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof TaskRelatedDeal
     */
    'property'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof TaskRelatedDeal
     */
    'agent'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof TaskRelatedDeal
     */
    'notes'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDeal
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDeal
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDeal
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof TaskRelatedDeal
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof TaskRelatedDeal
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDeal
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof TaskRelatedDeal
     */
    'localizations'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

