/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ClientStageCustomersInnerDealsInnerPropertyImagesInner } from './client-stage-customers-inner-deals-inner-property-images-inner';

/**
 * 
 * @export
 * @interface TaskRelatedDealStatusCustomersInnerNotesInnerProperty
 */
export interface TaskRelatedDealStatusCustomersInnerNotesInnerProperty {
    /**
     * 
     * @type {number}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'propertyType'?: TaskRelatedDealStatusCustomersInnerNotesInnerPropertyPropertyTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'location'?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'price'?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'area'?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'bedrooms'?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'bathrooms'?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'status'?: TaskRelatedDealStatusCustomersInnerNotesInnerPropertyStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'description'?: string;
    /**
     * 
     * @type {Array<ClientStageCustomersInnerDealsInnerPropertyImagesInner>}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'images'?: Array<ClientStageCustomersInnerDealsInnerPropertyImagesInner>;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'listedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'deals'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'notes'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>}
     * @memberof TaskRelatedDealStatusCustomersInnerNotesInnerProperty
     */
    'localizations'?: Array<ArticleCategoriesInnerProductImagesInnerRelatedInner>;
}

export const TaskRelatedDealStatusCustomersInnerNotesInnerPropertyPropertyTypeEnum = {
    Apartment: 'apartment',
    House: 'house',
    Land: 'land',
    Villa: 'villa',
    Commercial: 'commercial',
    Other: 'other'
} as const;

export type TaskRelatedDealStatusCustomersInnerNotesInnerPropertyPropertyTypeEnum = typeof TaskRelatedDealStatusCustomersInnerNotesInnerPropertyPropertyTypeEnum[keyof typeof TaskRelatedDealStatusCustomersInnerNotesInnerPropertyPropertyTypeEnum];
export const TaskRelatedDealStatusCustomersInnerNotesInnerPropertyStatusEnum = {
    Available: 'available',
    Sold: 'sold',
    Pending: 'pending',
    OffMarket: 'off-market'
} as const;

export type TaskRelatedDealStatusCustomersInnerNotesInnerPropertyStatusEnum = typeof TaskRelatedDealStatusCustomersInnerNotesInnerPropertyStatusEnum[keyof typeof TaskRelatedDealStatusCustomersInnerNotesInnerPropertyStatusEnum];


