/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleCategoriesInnerProductImagesInnerRelatedInner } from './article-categories-inner-product-images-inner-related-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedUserComponent } from './shared-user-component';
// May contain unused imports in some cases
// @ts-ignore
import type { TestimonialLocalizationsInner } from './testimonial-localizations-inner';

/**
 * 
 * @export
 * @interface Testimonial
 */
export interface Testimonial {
    /**
     * 
     * @type {number}
     * @memberof Testimonial
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Testimonial
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Testimonial
     */
    'text'?: string;
    /**
     * 
     * @type {SharedUserComponent}
     * @memberof Testimonial
     */
    'user'?: SharedUserComponent;
    /**
     * 
     * @type {string}
     * @memberof Testimonial
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Testimonial
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Testimonial
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Testimonial
     */
    'createdBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {ArticleCategoriesInnerProductImagesInnerRelatedInner}
     * @memberof Testimonial
     */
    'updatedBy'?: ArticleCategoriesInnerProductImagesInnerRelatedInner;
    /**
     * 
     * @type {string}
     * @memberof Testimonial
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<TestimonialLocalizationsInner>}
     * @memberof Testimonial
     */
    'localizations'?: Array<TestimonialLocalizationsInner>;
}

