generatorName: typescript-fetch
inputSpec: ./tmp/openapi-spec.yaml
outputDir: ./lib/services
apiPackage: api
modelPackage: models
additionalProperties:
  usePromises: true
  withInterfaces: true
  supportsES6: true
  useSingleRequestParameter: true
  withInterfaces: true
  useObjectParameters: false