http:
  routers:
    dashboard:
      rule: (Host(`traefik.{{ env "BASE_DOMAIN" }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`)))
      service: api@internal
      middlewares:
        - basic-auth
      tls:
        certResolver: myresolver
    strapi:
      rule: Host(`admin.{{ env "BASE_DOMAIN" }}`)
      service: strapi@docker
      middlewares:
        - rate-limit
        - https-redirect
      tls:
        certResolver: myresolver
      entryPoints:
        - websecure
    nextjs:
      rule: Host(`beta.{{ env "BASE_DOMAIN" }}`)
      service: nextjs@docker
      middlewares:
        - rate-limit
        - https-redirect
      tls:
        certResolver: myresolver
      entryPoints:
        - websecure
    n8n:
      rule: Host(`n8n.{{ env "BASE_DOMAIN" }}`)
      service: n8n@docker
      middlewares:
        - rate-limit
        - https-redirect
      tls:
        certResolver: myresolver
      entryPoints:
        - websecure
    affine:
      rule: Host(`affine.{{ env "BASE_DOMAIN" }}`)
      service: affine@docker
      middlewares:
        - rate-limit
        - https-redirect
      tls:
        certResolver: myresolver
      entryPoints:
        - websecure
    portainer:
      rule: Host(`portainer.{{ env "BASE_DOMAIN" }}`)
      service: portainer@docker
      middlewares:
        - rate-limit
        - https-redirect
      tls:
        certResolver: myresolver
      entryPoints:
        - websecure
    acme-challenge:
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - web
      service: api@internal
      priority: 100

  middlewares:
    basic-auth:
      basicAuth:
        usersFile: "/config/.htpasswd"
        realm: "Traefik 2 Basic Auth"
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    compress:
      compress: {}

certificatesResolvers:
  myresolver:
    acme:
      email: ${CER_ACME_EMAIL:-admin@localhost.dev}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web