http:
  routers:
    # Define a connection between requests and services
    dashboard:
      rule: (Host(`traefik.{{ env "BASE_DOMAIN" }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`)))
      service: api@internal
      middlewares:
        - basic-auth
      tls:
        certResolver: myresolver
    strapi:
      rule: Host(`beta-admin.{{ env "BASE_DOMAIN" }}`)
      service: strapi@docker
      middlewares:
        - rate-limit
        - https-redirectscheme
      tls:
        certResolver: myresolver
    nextjs:
      rule: Host(`beta.{{ env "BASE_DOMAIN" }}`)
      service: nextjs@docker
      middlewares:
        - rate-limit
        - https-redirectscheme
      tls:
        certResolver: myresolver
    n8n:
      rule: Host(`n8n-beta.{{ env "BASE_DOMAIN" }}`)
      service: n8n@docker
      middlewares:
        - rate-limit
        - https-redirectscheme
      tls:
        certResolver: myresolver
    portainer:
      rule: Host(`portainer.{{ env "BASE_DOMAIN" }}`)
      service: portainer@docker
      middlewares:
        - rate-limit
        - https-redirectscheme
      tls:
        certResolver: myresolver
    acme-challenge:
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - web
      service: acme-challenge@internal
      priority: 100
  middlewares:
    basic-auth:
      basicAuth:
        usersFile: "/config/.htpasswd"
        realm: "Traefik 2 Basic Auth"
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
        # Loại trừ đường dẫn /.well-known/acme-challenge/
        regex: "^https?://(.*)/((?!\\.well-known/acme-challenge/).*)$"
        replacement: "https://${1}/${2}"
    compress:
      compress: {}

certificatesResolvers:
  myresolver:
    acme:
      email: "{{ env \"CER_ACME_EMAIL\" }}"
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory