name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies and set up both Strapi and Next.js
      - name: Install dependencies and setup
        run: |
          yarn setup

      # Seed data for Strapi
      - name: Seed Strapi data
        run: |
          cd strapi
          yarn seed

      # Build and start Strapi
      - name: Start Strapi
        run: |
          yarn strapi &
        env:
          NODE_ENV: development
          HOST: 0.0.0.0
          PORT: 1337
          PREVIEW_SECRET: ${{ secrets.STRAPI_PREVIEW_SECRET }}
          APP_KEYS: ${{ secrets.APP_KEYS }}
          API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
          TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }}
          ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          STRAPI_ADMIN_CLIENT_PREVIEW_SECRET: ${{ vars.NEXT_PREVIEW_SECRET }}
          STRAPI_ADMIN_CLIENT_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      # Wait for Strapi to be ready
      - name: Wait for Strapi
        run: |
          npx wait-on http://localhost:1337

      # Build Next.js
      - name: Build Next.js
        run: |
          yarn next
        env:
          PREVIEW_SECRET: ${{ secrets.NEXT_PREVIEW_SECRET }}
          STRAPI_ADMIN_CLIENT_URL: ${{ vars.STRAPI_ADMIN_CLIENT_URL }}
      # Run tests (if any)
      - name: Run tests
        run: |
          cd next
          yarn test